spark.master                     spark://spark-master:7077

spark.eventLog.enabled           true
spark.eventLog.dir               file:/tmp/spark-events

spark.sql.extensions             io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog  org.apache.spark.sql.delta.catalog.DeltaCatalog


spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.sql.adaptive.enabled       true
spark.sql.session.timeZone       UTC

# S3 / MinIO config
spark.hadoop.fs.s3a.endpoint                      http://minio:9000
spark.hadoop.fs.s3a.path.style.access             true
spark.hadoop.fs.s3a.connection.ssl.enabled        false

spark.hadoop.fs.s3a.access.key ${env:AWS_ACCESS_KEY_ID}
spark.hadoop.fs.s3a.secret.key ${env:AWS_SECRET_ACCESS_KEY}

spark.hadoop.fs.s3a.impl                          org.apache.hadoop.fs.s3a.S3AFileSystem

# importante para containers
spark.driver.bindAddress          0.0.0.0

spark.driver.extraJavaOptions -Dcom.amazonaws.services.s3.enableV4
spark.executor.extraJavaOptions -Dcom.amazonaws.services.s3.enableV4


spark.sql.catalogImplementation         hive
spark.hadoop.hive.metastore.uris        thrift://hive-metastore:9083